name: Delete Azure Storage Account

on:
  workflow_dispatch:  # Manual trigger

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Delete Storage Account
      run: |
        az storage account delete \
          --name ghactiondeploystdsa \
          --resource-group GHActionDeploy \
          --yes
